### ISSUE TITLE
Some examples don't work in version 0.6.0

### ISSUE THREAD

**Issue by SongshGeo** [projectmesa/mesa-geo#169]
**Describe the bug**

`mesa runserver` doesn't work in example `rainfall`  and `population`.

dependencies' version: `mesa_geo = 0.6.0, mesa = "^2.1.2"`
`rasterio = "1.3.8.post2"`

```
Traceback (most recent call last):
  File "/Users/songshgeo/Documents/VSCode/mesa_geo/examples/rainfall/run.py", line 1, in <module>
    from rainfall.server import server
  File "/Users/songshgeo/Documents/VSCode/mesa_geo/examples/rainfall/rainfall/server.py", line 46, in <module>
    server = mesa.visualization.ModularServer(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songshgeo/Documents/VSCode/mesa_geo/.venv/lib/python3.11/site-packages/mesa_viz_tornado/ModularVisualization.py", line 354, in __init__
    self.reset_model()
  File "/Users/songshgeo/Documents/VSCode/mesa_geo/.venv/lib/python3.11/site-packages/mesa_viz_tornado/ModularVisualization.py", line 381, in reset_model
    self.model = self.model_cls(**model_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songshgeo/Documents/VSCode/mesa_geo/examples/rainfall/rainfall/model.py", line 77, in __init__
    self.space.set_elevation_layer("data/elevation.asc.gz", crs="epsg:4326")
  File "/Users/songshgeo/Documents/VSCode/mesa_geo/examples/rainfall/rainfall/space.py", line 37, in set_elevation_layer
    with gzip.open(elevation_gzip_file, "rb") as elevation_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/elevation.asc.gz'
```

**Expected behavior**
Open website and run server.

**To Reproduce**
It occurs when I run the example in a new virtual env:
```
pip install mesa-geo
mesa runserver rainfall
```

**Additional context**
It works when I switch to `0.5.0` version.

**Comment by wang-boyu** [comment]
Sorry about this. This is probably because all examples have been moved from this repo (https://github.com/projectmesa/mesa-geo/issues/128) to the `mesa-examples` repo under its [gis](https://github.com/projectmesa/mesa-examples/tree/main/gis) folder.

However these gis examples are not yet updated to mesa-geo v0.6.0 (https://github.com/projectmesa/mesa-examples/issues/59). There is a small issue with the old mesa-via-tornado visualization that labels and colors are missing (https://github.com/projectmesa/mesa-viz-tornado/issues/26).

**Comment by wang-boyu** [comment]
Should be fixed now that https://github.com/projectmesa/mesa-examples/pull/66 is merged.
